
# distress prompts to send distress audio to responsible organization
distress = [
        "Urgent help needed!",
    "Emergency situation!",
    "Immediate assistance required!",
    "Life-threatening crisis!",
    "Critical danger, respond ASAP!",
    "Please dispatch help now!",
    "Serious threat, intervene!",
    "Dangerous situation unfolding!",
    "Immediate intervention necessary!",
    "Report urgent incident!",
    "Please assist immediately!",
    "Respond to critical emergency!",
    "Life in imminent danger!",
    "Situation is dire!",
    "Need authorities on-site now!",
    "Call for emergency response!",
    "Respond urgently!",
    "Help required urgently!",
    "Immediate action required!",
    "Respond ASAP, urgent crisis!",
    "Critical incident, respond now!",
    "Dispatch help immediately!",
    "Dangerous circumstances, act fast!",
    "Request immediate assistance!",
    "Urgent situation, deploy responders!",
    "Emergency, need help now!",
    "Serious trouble, call authorities!",
    "Dangerous situation, please help!",
    "Immediate support necessary!",
    "Report critical incident!",
    "Life at risk, respond urgently!",
    "Seeking help for dire situation!",
    "Respond quickly, urgent situation!",
    "Immediate intervention needed!",
    "Crisis unfolding, respond now!",
    "Urgent call for assistance!",
    "Notify authorities, immediate!",
    "Threat escalating, act now!",
    "Emergency alert, respond urgently!",
    "Urgent distress, send help!",
    "Dangerous conditions, please respond!",
    "Critical help required!",
    "Emergency assistance needed!",
    "Time-sensitive crisis, act now!",
    "Report life-threatening situation!",
    "Urgent distress signal, respond!",
    "Situation is critical, respond fast!",
    "Requesting immediate intervention!",
    "Crisis situation, respond urgently!",
    "Life in peril, respond immediately!",
    "Notify authorities, urgent!",
    "Emergency response needed!",
    "Critical incident, act now!",
    "Immediate attention required!",
    "Urgent call for intervention!",
    "Emergency situation, respond fast!",
    "Need help urgently, critical!",
    "Request urgent support!",
    "Life-threatening issue, respond now!",
    "Act fast, dangerous situation!",
    "Critical distress, immediate response!",
    "Emergency alert, respond promptly!",
    "Urgent assistance required!",
    "Notify authorities, critical!",
    "Crisis unfolding, respond ASAP!",
    "I need help immediately!",
    "I think i am going to die!"
]